---
- name: Remove available service
  file:
    path: "{{ slowmonitoring['basedir'] }}/supervisor/available/*.ini"
    state: absent

- name: Remove enabled service
  file:
    path: "{{ slowmonitoring['basedir'] }}/supervisor/enabled/*.ini"
    state: absent

- name: Copy available service
  copy:
    src: "{{ item }}"
    dest: "{{ slowmonitoring['basedir'] }}/supervisor/available/"
    owner: root
    group: root
  with_fileglob:
    - "../supervisor/available/*.ini"

- name: Install services
  file:
    src: "{{ slowmonitoring['basedir'] }}/supervisor/available/{{ item }}.ini"
    dest: "{{ slowmonitoring['basedir'] }}/supervisor/enabled/{{ item }}.ini"
    state: link
    owner: root
    group: root
  with_items: "{{ services }}"
  when: services is defined
