---
- name: Install Git
  dnf:
    name: git
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install Git
  apt:
    name: git
    state: latest
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Vim
  dnf:
    name: vim
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install Vim
  apt:
    name: vim
    state: latest
  when: ansible_facts['os_family'] == 'Debian'

- name: Install archive tools
  dnf:
    name:
      - tar
      - gzip
      - bzip2
      - zip
      - unzip
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install archive tools
  apt:
    name:
      - tar
      - gzip
      - bzip2
      - zip
      - unzip
    state: latest
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Python3
  dnf:
    name:
      - python3
      - python3-pip
      - python3-virtualenv
    state: latest
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install Python3
  apt:
    name:
      - python3
      - python3-pip
      - virtualenv
      - python3-virtualenv
    state: latest
  when: ansible_facts['os_family'] == 'Debian'
